# Generated by Django 5.2 on 2025-04-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_size_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
